version: "3"
services:
  web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      DATABASE_URL: "${DB_URL}"
    secrets:
      - dburl
    depends_on:
      - db
    networks:
      - frontend
      - backend
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/pass
    secrets:
      - pass
    networks:
      - backend

secrets:
  pass:
    file: db_password.txt
  dburl: 
    file: db_url.txt

networks:
  frontend:
  backend: